### ISSUE TITLE
Document the browsers list, including the compact strings

### ISSUE THREAD

**Issue by leobalter** [browserstack/browserstack-runner#113]
The README documentation only points a link to the supported browsers without proper documenting how to use them.

Also, I can't find a list of the current support for compact browsers list anywhere.

**Comment by foxx** [comment]
+1 for this, incredibly frustrating

**Comment by foxx** [comment]
[This](https://www.browserstack.com/automate/node) form seems to generate the data needed, but it's a bit fiddly to use. I'd much rather have a bulk configurator, e.g. select the platforms you want, then it generates the browserstack.json `browsers` attribute for you.

**Comment by TehShrike** [comment]
Yes, please, what are all the valid short names?

**Comment by tchakabam** [comment]
wrote a little tool to help that: https://github.com/tchakabam/browserstack-select

**Comment by shirish87** [comment]
@leobalter @foxx @TehShrike, please have a look at the [updated README](https://github.com/browserstack/browserstack-runner/blob/cc968e6d4de7a152bbe8bfceb324e4a8ff960c07/README.md#browsers-parameter) and let me know if there's more scope for improvement. Thanks.

@tchakabam, `browser-select` looks useful. Probably makes sense to ship runner with at least a basic `browserstack.json` config generator. will look into it.

**Comment by foxx** [comment]
@shirish87 This still doesn't give us a list of the available browser configs.

**Comment by tchakabam** [comment]
@shirish87 feel free to get back to me if you want to collaborate on this!

**Comment by shirish87** [comment]
@foxx Not sure I understand. Beyond the field names (`browser`, `browser_version`, `os`, `os_version`), a few quirks aside, it's just a matter of looking up names in the [list of browsers](https://www.browserstack.com/list-of-browsers-and-platforms?product=automate) and creating the config.
I guess the compact browser config is what is creating some confusion.

@tchakabam will get back to you on this. Thanks!

**Comment by foxx** [comment]
@shirish87 How can you expect someone to know that the required JS value is `ie_11`, when the page you linked to does not show that value anywhere? Explain to me your thought process of how someone can derived that value from the instructions you have given

**Comment by shirish87** [comment]
Okay, so "ie_11" is shorthand for something that would otherwise be specified as:
````
{
  "browser": "ie",
  "browser_version": "11",
  "os": "Windows",
  "os_version": "10"
}
````

The [compact browser configuration](https://github.com/browserstack/browserstack-runner#compact-browsers-configuration) section specifies `[browser]_[version]` as a valid shorthand, i.e. you could use `ie_11`.

I'd be more than happy to accept a PR that does a better job of explaining this. But the current description seems decent.

**Comment by TehShrike** [comment]
If that's all there is, it might just be worth noting "The short name is `browser_name_1_1`, with the browser name lowercased, and spaces and periods converted to underscores".  You probably want to note that the names on [the doc page](https://www.browserstack.com/list-of-browsers-and-platforms) are canonical so that people know to use `ie` instead of `internet_explorer`.

**Comment by foxx** [comment]
@shirish87 You should look at how SauceLabs have done it, see [here], far more superior.

[1]: https://wiki.saucelabs.com/display/DOCS/Platform+Configurator

![image](https://cloud.githubusercontent.com/assets/651797/12615386/4b32c02c-c4fd-11e5-908b-1a9e785bdb19.png)

**Comment by shirish87** [comment]
@TehShrike, the doc page does mention "ie" and not Internet Explorer. But anyway.

@foxx, we have a similar tool in [our documentation](https://www.browserstack.com/automate/node#setting-os-and-browser), but linking to that would've caused even more confusion since it is meant for our Selenium testing product. You may refer to it to get an idea of OS/browser combination, but it's not specific to JS Testing which is being used here.

We do plan to make it easier to generate configuration for runner, but in the meantime, you can have a look at [browser-select](https://github.com/tchakabam/browserstack-select).
