### ISSUE TITLE
Android browsers timeout

### ISSUE THREAD

**Issue by leobalter** [browserstack/browserstack-runner#114]
As seen at https://github.com/jquery/qunit/pull/773, the Android browsers are always returning a timeout from the runner.

**Comment by nakula** [comment]
@leobalter this issue still persists?

**Comment by ausi** [comment]
I tested the mobile browsers in a simple test project ([ausi/browserstack-runner-travis-test](https://github.com/ausi/browserstack-runner-travis-test)) with the following results:

Android 1.5, 1.6, 2.2, 2.3, 4.1, 4.2 and iOS 8.3 are working fine.
[Project branch](https://github.com/ausi/browserstack-runner-travis-test/tree/mobile-working), [Travis build](https://travis-ci.org/ausi/browserstack-runner-travis-test/builds/77708273)

Android 4.3 and 4.4 fail with an error:

```
node_modules/browserstack-runner/lib/server.js:240
worker.getTestBro
       ^
TypeError: undefined is not a function
    at reportHandler (/node_modules/browserstack-runner/lib/server.js:240:140)
    at IncomingMessage.<anonymous> (/node_modules/browserstack-runner/lib/server.js:306:46)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

[Project branch](https://github.com/ausi/browserstack-runner-travis-test/tree/mobile-error), [Travis build](https://travis-ci.org/ausi/browserstack-runner-travis-test/builds/77708061)

Android 4.0, 5.0 and iOS 6.1, 7.0 run in a timeout.
[Project branch](https://github.com/ausi/browserstack-runner-travis-test/tree/mobile-timeout), [Travis build](https://travis-ci.org/ausi/browserstack-runner-travis-test/builds/77709262)

**Comment by shirish87** [comment]
@ausi, thanks for reporting these issues.

Android 4.3 (Amazon Kindle Fire HDX 7) fails gloriously due to a backend issue that should be resolved soon. If you need a fix urgently, please have a look at [my fork](https://github.com/shirish87/browserstack-runner-travis-test/tree/mobile-error) or [Travis](https://travis-ci.org/shirish87/browserstack-runner-travis-test/builds/77954141).

Android 4.0 is defaulting to one of the Kindle Fire tablets which has a known issue working with tunnels. 
Looks like Android 5.0 has some stability issues too. will look into it and report back. 
[mobile-timeout](https://github.com/shirish87/browserstack-runner-travis-test/tree/mobile-timeout) [Travis](https://travis-ci.org/shirish87/browserstack-runner-travis-test/builds/77961038)

iOS 6.1, 7.0 seem to be stuck in queue. should be resolved soon.

These aren't issues specific to Travis runs though. These also occur during local runs. : )

**Comment by tr4n2uil** [comment]
Closing, please reopen if issue still happening.
