### ISSUE TITLE
Mocha v3 support

### ISSUE THREAD

**Issue by paulfalgout** [browserstack/browserstack-runner#185]
It looks like mocha 3 may not be supported.  This https://github.com/browserstack/browserstack-runner/pull/179 might fix it, but what I'm seeing is only the passing test stat is getting recorded and all other values are showing up `NaN`  This means if a test fails, it doesn't fail the run.

**Comment by AlexanderOMara** [comment]
Mocha version 4 also seems to be non-functional, as I just discovered while attempting to setup some Mocha unit tests.

**Comment by mohitmun** [comment]
@AlexanderOMara Mocha v4 is functional. Can you provide me more details on what broke when you were trying to setup tests?
One issue which I figure was with [url.js](https://github.com/browserstack/url.js). we use this repo to conduct [integration tests](https://github.com/browserstack/browserstack-runner/blob/master/tests/test.rb). testing url.js against mocha 4 would report zero tests passed. this is because url.js has some [node runtime check](https://github.com/browserstack/url.js/blob/master/test/get.js#L25)
```
if ( typeof require == "function" )
{
	var chai = require("chai");
	var url  = require("../url");
}
```
 which would conflict with Mocha v4(as it had function named 'require' defined in it). when removing above check, it started working as expected. 
I also tested against v3 and v5. checked again all minor and major versions. 
Correct me if I have missed something.

Closing this issue for now, reopen with more details if issue persists.
