### ISSUE TITLE
broken (Uncaught Error: Error getting browsers list from BrowserStack)

### ISSUE THREAD

**Issue by DanielRuf** [browserstack/browserstack-runner#221]
It seems the Browserstack API can not be accessed anymore.

All instances fail.

See your current CI status:

https://travis-ci.org/browserstack/browserstack-runner/jobs/643758434#L320

**Comment by DanielRuf** [comment]
No relevant status at https://status.browserstack.com/

**Comment by DanielRuf** [comment]
Hi, we still have this issue. See https://travis-ci.com/foundation/foundation-sites/jobs/286429985#L349

**Comment by RohanImmanuel** [comment]
Hi @DanielRuf 

**Regarding the exception "throw new Error('Error getting browsers list from BrowserStack')"  seen in**
https://travis-ci.org/browserstack/browserstack-runner/jobs/643758434#L320 

This exception occurs when an incorrect BrowserStack Access Key is passed in the config or from the environment variable when the tests are executed. 

You can check the BrowserStack Credentials from the link: https://www.browserstack.com/accounts/settings.

I want to share that the same behavior is encountered in the BrowserStack's Travis CI Build executions as the BrowserStack credentials have been updated, and the tests are executing successfully.
<br/>
**Regarding your Travis CI Build execution**
https://travis-ci.com/foundation/foundation-sites/jobs/286481000#L340

I want to share that the behavior was encountered due to a bad deploy. The engineering team has reverted the changes from their side, and you should not reencounter this behavior.

**Comment by DanielRuf** [comment]
As discussed with the support on email it works again now after the Browserstack team fixed their setup.
