### ISSUE TITLE
Create a history file during/after runs

### ISSUE THREAD

**Issue by parisholley** [browserstack/browserstack-runner#55]
Create a JSON file that can be loaded in a subsequent run to allow the user to re-run failed tests (could implement in CLI similar to how VIM behaves when it detects a swap file).

**Comment by shirish87** [comment]
@parisholley, while your dev use-case is valid, most devs are comfortable re-testing with all browsers just in case their changes cause a regression.

For (2) – BrowserStack worker timeouts, etc. should not be the reason for having a retry feature, imho. If these issues do ever occur, they will be fixed in the service.
Thanks.
