### ISSUE TITLE
Fix escaping in lib/utils escapeSpecialChars()

### ISSUE THREAD

**Issue by jzaefferer** [browserstack/browserstack-runner#99]
A leftover from #97. Needs a separate fix. I don't know what input it deals with. Currently running `npm test` produces this error:

```
lib/utils.js: line 11, col 22, Bad or unnecessary escaping.
```

A unit test for this method would help a lot. The fix itself should be trivial, probably removing one of the slashes. But that needs a way to verify the correctness of the method.

The purpose of the method:

> json response (stack trace etc) we send back from browser to runner sometimes have newline and single quote chars which confuses the JSON.parse(). So, escapeSpecialChars handles that for us.

**Comment by shirish87** [comment]
So, `.replace(/\\s/g, '\s')` obviously doesn't do anything. Using `\s` as a replacement would never achieve anything since it isn't a control character but a Regex metacharacter that matches all kinds of whitespace characters.

Anyway, the high-level objective of `escapeSpecialChars()` is to sanitize input for `JSON.parse()`, removing any escape sequences. Low-level reason is that the stack trace returned from the browser - in case of errors - contains escape sequences such as \n and is effectively invalid JSON.

I think we should [cover the general case](http://stackoverflow.com/questions/4253367/how-to-escape-a-json-string-containing-newline-characters-using-javascript) instead of guarding against escape sequences that only occur in our stack traces.

Thoughts?

https://gist.github.com/shirish87/d257e1d43ff91e4522be

**Comment by jzaefferer** [comment]
Agreed, covering general case makes sense.

May want to optimize that replace a bit, like this https://github.com/jquery/jquery-ui/blob/cd6c751b88313ac1fa2e0fb46d7668ca6ce0f4b1/ui/autocomplete.js#L601 (which is for regex, but the `\\$&` should work here as well.

**Comment by shirish87** [comment]
As it turns out, the `&$` reference doesn't work for this specific case involving escape sequences, primarily because `'\\n' !== ('\\' + '\n')`.
Also thought of covering quotes and others, but we'd risk breaking JSON.

Ideally, the *client* shouldn't be sending JSON strings with escape sequences. Maybe we should filter these [before they are JSON.stringify'd](https://github.com/browserstack/browserstack-runner/blob/a8cfbb329e347e07478dd1713405bd9843f5dde7/lib/_patch/browserstack.js#L26) in the browser?

For now, I think the `escapeSpecialChars` approach is good enough. Passes JSHint. : )
